Add navbar
Tampereen-Urheilusukeltajat/Blenderi-UI pull request #4
Opened 2022-10-10 19:18 UTC by Tiikewi

![Screenshot 2022-10-10 at 22 17 32](https://user-images.githubusercontent.com/45666268/194937594-bfe2fb1c-4401-408e-acf2-7745605b6cf6.png)

2022-10-11 16:58 UTC, Akzuu commented on src/views/Navbar.tsx
> +  console.log('Kirjaudu ulos clicked.');
Vähän häiritsee finglish. Käytetään koodissa englantia

```suggestion
  console.log('Log out button clicked');
```

2022-10-11 16:58 UTC, Akzuu commented on src/views/Navbar.tsx
> +  return path !== '/' && path !== '/register' ? (
Tämmösen listan ylläpito voi käydä ärsyttäväksi jos näitä tulee aina lisää. Nopeana vaihtoehtona tuli mieleen tarkastella käyttäjän kirjautumista, mutta se ei ole vielä valmista.

Olkoon näin, mutta lisäisin TODO:n missä ilmaistaisiin tarve refaktoroinnille

2022-10-11 16:58 UTC, Akzuu commented on tests/navbar.test.ts
> +});
Nää vois heittää kaikki describen sisälle

2022-10-11 18:40 UTC, Tiikewi reviewed
Onko tässä testiflow dockerfilessa ja composessa mitään järkeä? :D

2022-10-13 10:31 UTC, ilesoft requested changes

2022-10-13 10:31 UTC, ilesoft commented on .dockerignore
> +node_modules
Rivinvaihto loppuun

2022-10-13 14:52 UTC, Akzuu approved these changes

2022-10-13 14:52 UTC, Akzuu commented on src/styles/navbar/navbar.sass
> +$activeTextColor: black
Use HEX

2022-10-13 14:52 UTC, Akzuu commented on tests/navbar.test.ts
> +    expect(await page.locator('.nav').count()).toEqual(0);
Instead of count use 

```suggestion
    expect(await page.locator('.nav')).not.toExist();
```

2022-10-13 15:25 UTC, ilesoft approved these changes
En ehtiny kattoo...LGTM

2022-10-13 15:27 UTC, merged