Käyttäjänhallinta näkymän pohja
Tampereen-Urheilusukeltajat/Blenderi-UI pull request #6
Opened 2022-10-13 20:01 UTC by toppeh

Käyttäjänhallinta (admin) pohja
Muokattu myös start scriptiä käynnistämään serverin porttiin 3003, jotta se olisi eri portissa kuin bäkkäri.

2022-10-14 18:06 UTC, jkaariain reviewed
Näkymä näyttää hyvältä ja sen asettelua voidaan kohentaa jatkossa, kunhan saadaan näkymät valmiiksi (navbar, etc.). package.json tiedostossa PORT=3003 ei taida tomia, jos ajaa `npm run start` komennon Windows-ympäristössä.

2022-10-15 09:55 UTC, Akzuu requested changes

2022-10-15 09:55 UTC, Akzuu commented on src/components/UserControlTable.tsx
> +        </tbody>
Tän vois irrottaa omaksi komponentiksiin mihin annetaan propseina käyttäjät

2022-10-15 09:55 UTC, Akzuu commented on src/index.sass
> +  top: 200px
Oksettavaa. Käytäppä flexboxia 

https://css-tricks.com/snippets/css/a-guide-to-flexbox/

2022-10-15 09:55 UTC, Akzuu commented on package.json
> +    "start": "PORT=3003 react-scripts start",
Oksettavaa. PORT veks

2022-10-15 09:56 UTC, Akzuu commented
Laitatko PR kuvaukseen linkin Figmaan mihin tää perustuu sekä kuvan toteutuksesta

2022-10-15 09:56 UTC, Akzuu commented on package.json
> +    "start": "PORT=3003 react-scripts start",
Bäkkärin porttia voi muokata .env konffista

2022-10-15 09:57 UTC, ilesoft requested changes, later dismissed

2022-10-15 09:57 UTC, ilesoft commented on src/views/UserControl.tsx
> +export default UserControl;
Newline

2022-10-15 09:57 UTC, ilesoft commented on src/components/UserControlTable.tsx
> +};
Newline

2022-10-15 11:10 UTC, ilesoft commented
Saisko nää konfliktit pois enen kuin PR avataan?

2022-10-18 12:44 UTC, toppeh commented on src/components/UserControlTable.tsx
> +        </tbody>
Minusta tää on ihan hyvä näinkin

2022-10-18 15:34 UTC, toppeh commented on src/components/UserControlTable.tsx
> +        </tbody>
Varsinkin, koska samanlaista taulua ei ole muissa näkymissä, jolloin sitä ei tule käytettyä uudelleen.

2022-10-20 05:51 UTC, Akzuu approved these changes

2022-10-20 05:51 UTC, Akzuu commented on playwright.config.ts
> +    },
Jätetään selaimista tarkistukseen vain chrome niin pipelinen ajot hieman nopeutuu.

2022-10-20 05:51 UTC, Akzuu commented on src/components/UserManagementTable.tsx
> +}; */
Pitäskö tää poistaa?

2022-10-20 05:51 UTC, Akzuu commented on src/components/UserManagementTable.tsx
> +}; */
Se synkka ei välttämättä oo tulossa muuten ihan heti :D

2022-10-20 05:51 UTC, Akzuu commented on src/components/UserManagementTable.tsx
> +  }, []);
Mikäs ajatus tässä on?

2022-10-20 05:51 UTC, Akzuu commented on playwright.config.ts
> +    },
Eli tän voi kommentoida pois

2022-10-20 11:42 UTC, toppeh commented on src/components/UserManagementTable.tsx
> +  }, []);
Ajatus on siinä, että muuten lintteri valittaa että setUsers'ia ei käytetä

2022-10-20 14:17 UTC, merged