Tayttonakyman pohja
Tampereen-Urheilusukeltajat/Blenderi-UI pull request #7
Opened 2022-10-15 12:45 UTC by jkaariain

2022-10-16 08:29 UTC, Akzuu requested changes

2022-10-16 08:29 UTC, Akzuu commented on src/views/LogBook.tsx
> +  };
`useCallback` for these functions

2022-10-16 08:29 UTC, Akzuu commented on src/views/LogBook.tsx
> +  lisatiedot?: string;
Näissä vois käyttää englantia

2022-10-16 08:29 UTC, Akzuu commented on src/views/LogBook.tsx
> +  pvm: Date;
Sama kun yllä

2022-10-16 08:29 UTC, Akzuu commented on src/styles/navbar/navbar.sass
> + text-align: center*/
Jäikö vahingossa kommentoiduksi? Voi poistaa jos tarkoituksella pois

2022-10-16 08:29 UTC, Akzuu commented on src/styles/navbar/navbar.css
> + * text-align: center*/
Kommentoidut asiat veks

2022-10-16 08:29 UTC, Akzuu commented on src/components/LogBookNewEvent.tsx
> +          onChange={(e) => (props.eventRow.pullo = e.target.value)}
Nää `onChange`t vois tehdä omiksi funktioiksi, vaikkeivat nyt olekkaan kovin isoja juttuja

2022-10-16 08:29 UTC, Akzuu commented on src/components/LogBookNewEvent.tsx
> +const EventRows: FC<EventRowsI> = (props): JSX.Element => {
Pitäskö näitä splittailla omiksi tiedostoiksi?

2022-10-16 08:29 UTC, Akzuu commented on src/components/LogBookNewEvent.tsx
> +            //alert(JSON.stringify(values, null, 2));
Poisto

2022-10-16 08:29 UTC, Akzuu commented on src/components/LogBookNewEvent.tsx
> +        }}
Tässä alkaa ainakin olla niin paljon logiikkaa, että tästä sais oman funktion `handleSubmit`. Koitetaan välttää JSX seassa olevia handlereita

2022-10-16 09:58 UTC, jkaariain commented on src/views/LogBook.tsx
> +  lisatiedot?: string;
> Näissä vois käyttää englantia

Mitä englanninkielisiä vastikkeita ehdottaisit?

2022-10-16 11:42 UTC, Akzuu commented on src/views/LogBook.tsx
> +  lisatiedot?: string;
Esim divingCylinder, gas, fillingPressure, additionalInformation ?

Ajatus lähinnä, että ainoastaan loppukäyttäjälle näkyy suomea ja taustalla kaikki rullaa englanniksi.

2022-10-16 13:56 UTC, Akzuu commented on src/styles/logbook/LogBook.css
> +/*# sourceMappingURL=LogBook.css.map */
Tutkittiin muuten tätä aiemmin ja todettiin, että haluttaisiin compileta nää tyylit ilman source mappia. Siellä on readme.md:n ohjeisiin lisätty lippu tätä varten `--no-source-map`

2022-10-17 13:17 UTC, Akzuu approved these changes

2022-10-17 13:17 UTC, Akzuu commented on src/components/LogBookNewEvent.tsx
> +    props.events.forEach((x) => values.push(x));
x sijasta voisi käyttää kuvaavampaa nimeä, esim `event`. Sama homma oli myös EventRows.tsx.

Voit myös tuolla funktion parametreissa tiputtaa propsin pois jos avaat ne propsit näin `const LogBookNewEvent: FC<LogBookNewEventProps> = ({ events }): JSX.Element => {...}`

2022-10-17 13:17 UTC, Akzuu commented on src/components/LogBookHistoryRow.tsx
> +        bar
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator
 
```suggestion
{props.historyRow.compressedAir ??  0}{' '}bar
```

2022-10-17 13:17 UTC, Akzuu commented on src/components/LogBookHistoryRow.tsx
> +        {props.historyRow.oxygen != null ? props.historyRow.oxygen : 0} bar
Nullis coalescing operator

2022-10-17 13:17 UTC, Akzuu commented on src/components/LogBookHistoryRow.tsx
> +        {props.historyRow.helium != null ? props.historyRow.helium : 0} bar
Nullis coalescing operator

2022-10-17 13:17 UTC, Akzuu commented on src/components/LogBookHistoryRow.tsx
> +      <td>{props.historyRow.argon != null ? props.historyRow.argon : 0} bar</td>
Nullis coalescing operator

2022-10-17 13:17 UTC, Akzuu commented on src/components/LogBookHistoryRow.tsx
> +        {props.historyRow.additionalInformation != null
Nullis coalescing operator

2022-10-17 13:17 UTC, Akzuu commented on src/components/LogBookNewEvent.tsx
> +            x.additionalInformation != null ? x.additionalInformation : '-',
Nullis coalescing operator

2022-10-17 13:35 UTC, Akzuu commented
Ainiin, testejä olis hyvä tehdä. Koska toiminnallisuus vielä uupuu, riittänee pohjaksi joka testaa että sivu renderöidään oikeasta osoitteesta ja että navbarilla kykenee navigoimaan näkymään.

2022-10-20 05:47 UTC, merged