Warn user about invalid and expired links
Tampereen-Urheilusukeltajat/Blenderi-UI pull request #76
Opened 2023-09-23 23:37 UTC by ilesoft

Liittyy https://github.com/Tampereen-Urheilusukeltajat/Blenderi-Backend/pull/92

2023-09-25 05:58 UTC, ile-monad commented on src/components/ResetPassword/ResetPasswordForm.tsx
> +    tokenCreationTime.getTime() + 10 * 60000
Nojoo tähän vois kyllä laittaa jotain selvennystä siitä, mitä noi taikaluvut on

2023-09-25 06:46 UTC, Akzuu commented on src/components/ResetPassword/ResetPasswordForm.tsx
> +    tokenCreationTime.getTime() + 10 * 60000
Juu se olis ihan jees

2023-09-25 06:47 UTC, Akzuu commented on src/components/ResetPassword/ResetPasswordForm.tsx
> +    tokenCreationTime.getTime() + 10 * 60000
Tälle funkkarille voi ylipäänsä antaa jonkun yhden lauseen sanallisen selityksen mikä kertoo millon linkki on meidän mielestä aktiivinen

2023-09-25 07:00 UTC, Akzuu requested changes

2023-09-25 07:00 UTC, Akzuu commented on src/views/ResetPassword/ResetPassword.tsx
> +  }
Tässä on hieman toistuvaa koodia. Muuttuvat asiat on titlen ja p:n sisältö.

Mitä jos nää tallennettaisiinkin muuttujaan? Muuttujaan manipuloidaan sitten sopivat tekstit virhetilanteissa, defaulttina ne on sit ne mitä yleensäkin palautetaan eli `let title = "Salasanan palauttaminen"` ja `let body = "Aseta uusi salasana"`

2023-09-25 07:00 UTC, Akzuu commented on src/views/ResetPassword/ResetPassword.tsx
>      </div>
```suggestion
    <div className={styles.resetPassword}>
      <header className={styles.header}>
        <h1>{title}</h1>
        <p>{body}</p>
      </header>
      {linkIsValid && (
        <ResetPasswordForm
        token={token}
        userId={userId}
        tokenCreationTimestamp={tokenCreationTimestamp}
      />
      )}
    </div>
```

2023-09-25 07:15 UTC, ilesoft commented on src/components/ResetPassword/ResetPasswordForm.tsx
> +    tokenCreationTime.getTime() + 10 * 60000
tästähän me jo puhuttiin

2023-09-27 19:01 UTC, ilesoft commented on src/views/ResetPassword/ResetPassword.tsx
> +  }
Odotetaan kolmatta ja sitte refactoroidaan

2023-09-27 19:03 UTC, ilesoft commented on src/views/ResetPassword/ResetPassword.tsx
>      </div>
Mikä juttu?

2023-09-28 17:24 UTC, ilesoft commented on src/views/ResetPassword/ResetPassword.tsx
> +  }
Tästä innostuin tarkastelemaan tuota "toisteista" koodia ja pienentämään sitä hieman.

2023-09-28 17:26 UTC, ilesoft commented on src/views/ResetPassword/ResetPassword.tsx
>      </div>
En tykkää ehdottamastasi abstractiosta

2023-09-28 17:54 UTC, Akzuu approved these changes

2023-09-28 18:54 UTC, merged